variable "postgres_rds_password" {}
variable "env_name" {} 
variable "region" {} 
variable "vpc_id" {}
variable "base_domain" {}
variable "rds_replica_enabled" {}
variable "vpc_security_group_ids" {}
variable "postgres_rds_instance_class" {}
variable "db_subnet_group_name" {}
variable "parameter_group_name" {}
variable "rds_multi_az_enabled" {}
variable "rds_deletion_protection" {}
variable "rds_storage_type" {}
variable "rds_storage_size" {}
variable "rds_iops" {}
variable "rds_provision_file" {}
variable "postgres_rds_replica_instance_class" {}
variable "rds_identifier" {}
variable "replica_rds_identifier" {}
variable "skip_final_snapshot" {}
variable "count" {}
variable "dns_rds_identifier" {}
