---
name: Validate terraform and terragrunt code

on: 
  push:
    paths:
      - '**.tf'
      - '**.tfvars'
      - '**/terragrunt.hcl'

env:
  terraform_version:  '1.7.4'
  terragrunt_version: '0.55.14'
  working_dir:        .

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Lint Terraform
        shell: bash
        run: |
          terraform fmt -check -recursive -diff
          if [[ $? !=  "0" ]]; then
            echo "Some terraform files need to be formatted. Run 'terraform fmt -recursive' to fix them.";
            exit 1;
          fi

  terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.terraform_version }}
          tg_version: ${{ env.terragrunt_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
