name: Validate terraform
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  validate_tf:
    name: Validate terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install TF
        run: |
          sudo apt install -y software-properties-common apt-transport-https
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt update
          sudo apt install -y terraform
          terraform -v
      - name: Validate TF
        run: |
          ROOT_DIR=$(pwd)
          FOLDERS=$(find . -type f -name '*.tf' -not -path "*.terraform/*" | sed -r 's|/[^/]+$$||' | sort | uniq)
          for f in $FOLDERS; do
            echo "Validating folder $f"
            cd $ROOT_DIR
            cd $f
            terraform init -input=false -no-color -backend=false
            terraform validate
            exitCode=$?
            if [ $exitCode -ne 0 ]; then
              echo "ERROR! $exitCode"
              exit $exitCode
            fi
          done
